/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlService = IDL.Service({
  'getDailyHoroscope' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], []),
  'getLoveHoroscope' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], []),
  'getNewPsychicReading' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getRandomGeneralReading' : IDL.Func([], [IDL.Text], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  return IDL.Service({
    'getDailyHoroscope' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], []),
    'getLoveHoroscope' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], []),
    'getNewPsychicReading' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getRandomGeneralReading' : IDL.Func([], [IDL.Text], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };